# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_geocodable}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Morrison", "Brandon Keepers"]
  s.date = %q{2009-10-21}
  s.description = %q{Simple geocoding for Rails ActiveRecord models. See the README for more details.}
  s.email = %q{info@collectiveidea.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "about.yml",
     "acts_as_geocodable.gemspec",
     "generators/geocodable_migration/USAGE",
     "generators/geocodable_migration/geocodable_migration_generator.rb",
     "generators/geocodable_migration/templates/migration.rb",
     "install.rb",
     "lib/acts_as_geocodable.rb",
     "lib/acts_as_geocodable/geocode.rb",
     "lib/acts_as_geocodable/geocoding.rb",
     "lib/acts_as_geocodable/remote_location.rb",
     "lib/acts_as_geocodable/tasks/acts_as_geocodable_tasks.rake",
     "rails/init.rb",
     "test/acts_as_geocodable_test.rb",
     "test/db/database.yml",
     "test/db/schema.rb",
     "test/fixtures/cities.yml",
     "test/fixtures/geocodes.yml",
     "test/fixtures/geocodings.yml",
     "test/fixtures/vacations.yml",
     "test/geocode_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/collectiveidea/acts_as_geocodable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple geocoding for Rails ActiveRecord models}
  s.test_files = [
    "test/acts_as_geocodable_test.rb",
     "test/db/schema.rb",
     "test/geocode_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
